apiVersion: v1.1
resources:
  - name: gitK53Certbot
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/k53certbot
  - name: pythonEnvK53Certbot
    type: declarativesystems/PythonEnv
    configuration:
      sourceArtifactory: artifactory # for resolving and publishing packages
      repositoryName: pypi

pipelines:
  - name: k53certbot
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker-local/pipelines"
            tag: "0.8.1"
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: pythonBuildAndDeploy
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: pythonEnvK53Certbot
            - name: gitK53Certbot
        execution:
          onExecute:
            - cd $res_gitK53Certbot_resourcePath
            - add_pipeline_variables k53CertbotVersion=$(make print_version)
            - make upload_artifactory

      - name: binary
        type: declarativesystems/ArtifactoryDownload
        configuration:
          affinityGroup: k53certbot
          sourceArtifactory: artifactory
          path: pypi-local/k53certbot/${k53CertbotVersion}/k53certbot-${k53CertbotVersion}-py3-none-any.whl
          integrations:
            - name: artifactory
          inputSteps:
            - name: pythonBuildAndDeploy
          inputResources:
            - name: gitK53Certbot
        execution:
          onStart:
            - cd $res_gitK53Certbot_resourcePath
            - add_pipeline_variables k53CertbotVersion=$(make print_version)

      - name: buildAndPushImage
        type: Bash
        configuration:
          affinityGroup: k53certbot
          inputResources:
            - name: gitK53Certbot
          integrations:
            - name: quayIo
          inputSteps:
            - name: binary
        execution:
          onExecute:
            - cd $res_gitK53Certbot_resourcePath
            - mkdir -p dist
            - cp $res_binary_resourcePath dist
            - podman login "$int_quayIo_url" --password $(echo "$int_quayIo_password") --username $(echo "$int_quayIo_username")

            - make image_build
            - make ci_image_push
          onFailure:
            - tree -L 4
            - env
