---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: some-app
  annotations:
    kubernetes.io/ingress.class: ambassador
  labels:
    app.kubernetes.io/name: some-app
spec:
  tls:
    - hosts:
        - example.yourdomain.com
      # https://github.com/datawire/ambassador/issues/1255
      secretName: tls-example-yourdomain-com
  rules:
    - host: example.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: some-app
                port:
                  number: 80
